server:
  port: 8001
spring:
  application:
    name: springcloud-common
 
#注册中心指向start    
eureka:
  instance:
    instance-id: springcloud-common
    appname: ${spring.application.name}
  client: 
    service-url: 
      defaultZone: http://admin:123456@192.168.24.135:8888/eureka/
#注册中心指向end
