server:
  port: 7000
#服务名字
spring:
  application:
    name: springcloud-config
  profiles:
    active: native
  cloud:
      config:
        server:
          native:
            search-locations: classpath:env/  # 搜索src/main/resource 下的env文件夹下的文件
 
              
#加入注册中心，实现高可用
eureka:
  client:
    service-url:
       defaultZone: http://admin:123456@192.168.24.135:8888/eureka/
  instance:
    prefer-ip-address: true
    instance-id: ${spring.cloud.client.ipAddress}:${server.port} 


